chat/urls.py
from django.urls import path, re_path

from .views import ThreadView, InboxView, ChatView

app_name = 'chat'
urlpatterns = [
    path("", InboxView.as_view()),
    re_path(r"^d/(?P<username>[\w.@+-]+)/", ThreadView.as_view()),
    path("chat/<slug:slug>/", ChatView.as_view(), name="chat"),
]

postap/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, re_path, include

urlpatterns = [
                  path('ajax_select/', include('ajax_select.urls')),
                  path('admin/', admin.site.urls),
                  path('', include('entries.urls')),
                  path('users/', include('users.urls')),
                  path('chats/', include('chat.urls')),
                  path('rp/', include('roleplay.urls')),
                  path('polls/', include('voting.urls')),
                  path(r'comments/', include('django_comments_xtd.urls')),
                  path('tinymce/', include('tinymce.urls')),
                  path('likes/', include('favorites.urls')),
                  path('api-auth/', include('rest_framework.urls')),
                  re_path(r'^uploads/', include('ckeditor_uploader.urls')),
                  # !| TEMPORARY APPS AND PATHS |!
                  #    ! DELETE BEFORE DEPLOY !

              ] + static(settings.STATIC_URL, docuent_root=settings.STATICFILES_DIRS)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

chat/models.py
from django.conf import settings
from django.db import models
from django.db.models import Q
from django.utils.html import format_html


class ThreadManager(models.Manager):
    def by_user(self, user):
        qlookup = Q(first=user) | Q(second=user)
        qlookup2 = Q(first=user) & Q(second=user)
        qs = self.get_queryset().filter(qlookup).exclude(qlookup2).distinct()
        return qs

    def get_or_new(self, user, other_username):  # get_or_create
        username = user.username
        if username == other_username:
            return None
        qlookup1 = Q(first__username=username) & Q(second__username=other_username)
        qlookup2 = Q(first__username=other_username) & Q(second__username=username)
        qs = self.get_queryset().filter(qlookup1 | qlookup2).distinct()
        if qs.count() == 1:
            return qs.first(), False
        elif qs.count() > 1:
            return qs.order_by('timestamp').first(), False
        else:
            Klass = user.__class__
            user2 = Klass.objects.get(username=other_username)
            if user != user2:
                obj = self.model(
                    first=user,
                    second=user2
                )
                obj.save()
                return obj, True
            return None, False


class Thread(models.Model):
    first = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='chat_thread_first')
    second = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='chat_thread_second')
    updated = models.DateTimeField(auto_now=True)
    timestamp = models.DateTimeField(auto_now_add=True)

    objects = ThreadManager()

    @property
    def room_group_name(self):
        return f'dialog_{self.id}'

    def broadcast(self, msg=None):
        if msg is not None:
            broadcast_msg_to_chat(msg, group_name=self.room_group_name, user='admin')
            return True
        return False


class Chat(models.Model):
    name = models.CharField(max_length=50, verbose_name="Название чата")
    slug = models.SlugField(verbose_name="Slug")
    in_chats = models.BooleanField(default=False, verbose_name="Выводить в списке чатов")
    roleplay = models.BooleanField(verbose_name="Чат ролевой игры", default=False)
    preview = models.ImageField(default="roleplay/default/campfire.jpg", upload_to="roleplay/campfire",
                                verbose_name="Превью")

    def icon_admin(self):
        return format_html(
            '<center><img href="{0}" src="{0}" height="100" width="100" style="border-radius: 100%" /></center>'.format(
                self.preview.url))

    icon_admin.allow_tags = True
    icon_admin.short_description = 'Иконка'

    @property
    def room_group_name(self):
        return f'chat_{self.id}'

    def broadcast(self, msg=None):
        if msg is not None:
            broadcast_msg_to_chat(msg, group_name=self.room_group_name, user='admin')
            return True
        return False

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Чат"
        verbose_name_plural = "Чаты"


class AbstractMessage(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name='sender', on_delete=models.CASCADE)
    message = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)

    class Meta:
        abstract = True


class DialogMessage(AbstractMessage):
    thread = models.ForeignKey(Thread, null=True, blank=True, on_delete=models.SET_NULL)


class ChatMessage(AbstractMessage):
    thread = models.ForeignKey(Chat, null=True, blank=True, on_delete=models.SET_NULL)

chat/forms.py
from django import forms


class ComposeForm(forms.Form):
    message = forms.CharField(
        widget=forms.TextInput(
            attrs={"class": "form-control"}
        )
    )

chat/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import Http404, HttpResponseForbidden
from django.views.generic import DetailView, ListView
from django.views.generic.edit import FormMixin

from .forms import ComposeForm
from .models import Thread, DialogMessage, Chat, ChatMessage


class InboxView(LoginRequiredMixin, ListView):
    template_name = 'chat/inbox.html'

    def get_queryset(self):
        return Thread.objects.by_user(self.request.user)


class ThreadView(LoginRequiredMixin, FormMixin, DetailView):
    template_name = 'chat/thread.html'
    form_class = ComposeForm
    success_url = './'

    def get_queryset(self):
        return Thread.objects.by_user(self.request.user)

    def get_object(self):
        other_username = self.kwargs.get("username")
        obj, created = Thread.objects.get_or_new(self.request.user, other_username)
        if obj == None:
            raise Http404
        return obj

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = self.get_form()
        return context

    def post(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return HttpResponseForbidden()
        self.object = self.get_object()
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        thread = self.get_object()
        user = self.request.user
        message = form.cleaned_data.get("message")
        DialogMessage.objects.create(user=user, thread=thread, message=message)
        return super().form_valid(form)


class ChatView(LoginRequiredMixin, FormMixin, DetailView):
    template_name = 'chat/chat.html'
    form_class = ComposeForm
    success_url = './'
    model = Chat

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = self.get_form()
        return context

    def post(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return HttpResponseForbidden()
        self.object = self.get_object()
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        thread = self.get_object()
        user = self.request.user
        message = form.cleaned_data.get("message")
        ChatMessage.objects.create(user=user, thread=thread, message=message)
        return super().form_valid(form)

chat/templates/chat/chat.html
{% extends "base.html" %}

{% block content %}
    <style>
        .msg {
            display: flex;
            align-items: flex-end;
            margin-bottom: 10px;
        }

        .msg:last-of-type {
            margin: 0;
        }

        .msg-img {
            width: 50px;
            height: 50px;
            margin-right: 10px;
            background: #ddd;
            background-repeat: no-repeat;
            background-position: center;
            background-size: cover;
            border-radius: 50%;
        }

        .msg-bubble {
            max-width: 450px;
            padding: 15px;
            border-radius: 15px;
            background: #ececec;
        }

        .msg-info {
            display: flex;
            justify-content: space-between;
            align-items: center;
            margin-bottom: 10px;
        }

        .msg-info-name {
            margin-right: 10px;
            font-weight: bold;
        }

        .msg-info-time {
            font-size: 0.85em;
        }

        .user-msg .msg-bubble {
            border-bottom-left-radius: 0;
        }

        .my-msg {
            flex-direction: row-reverse;
        }

        .my-msg .msg-bubble {
            background: #579ffb;
            color: #fff;
            border-bottom-right-radius: 0;
        }

        .my-msg .msg-img {
            margin: 0 0 0 10px;
        }

        .msger-inputarea {
            display: flex;
            padding: 10px;
            border-top: 2px solid #ddd;
            background: #eee;
        }

        .msger-inputarea * {
            padding: 10px;
            border: none;
            border-radius: 3px;
            font-size: 1em;
        }

        .msger-input {
            flex: 1;
            background: #ddd;
        }

        .msger-send-btn {
            margin-left: 10px;
            background: rgb(0, 196, 65);
            color: #fff;
            font-weight: bold;
            cursor: pointer;
            transition: background 0.23s;
        }

        .msger-send-btn:hover {
            background: rgb(0, 180, 50);
        }

    </style>
    <h3>Thread for {% if user != object.first %}{{ object.first }}{% else %}{{ object.second }}{% endif %}</h3>
    <div id='chat-items'>
        {% for chat in object.chatmessage_set.all %}
            <div class="msg {% if chat.user == user %}my{% else %}user{% endif %}-msg">
                <div
                        class="msg-img"
                        style="background-image: url({{ chat.user.avatar.url }})"></div>

                <div class="msg-bubble">
                    <div class="msg-info">
                        <div class="msg-info-name">{{ chat.user }}</div>
                        <div class="msg-info-time">{{ chat.timestamp|date:"d.m.y H:i" }}</div>
                    </div>

                    <div class="msg-text">
                        {{ chat.message }}
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>

    <form id='form' method='POST'> {% csrf_token %}
        {{ form.as_p }}
        <input type='submit' class='btn btn-primary'/>
    </form>



{% endblock %}
{% block javascript %}

    <script>
        let THIS_USERNAME = "{{ user.username }}";

        function find_sender(this_user, sended_user) {
            console.log(this_user, sended_user, this_user === sended_user);
            return this_user === sended_user ? "my" : "user";
        }

        $(document).ready(function () {
            // alert("jquery world")
            let formData = $("#form"),
                messageInput = $("#id_message"),
                chatItems = $('#chat-items'),
                loc = window.location,
                wsStart = "ws://";
            if (loc.protocol == "https:") {
                wsStart = "wss://";
            }
            let webSocketEndpoint = wsStart + loc.host + loc.pathname,  // ws : wss
                socket = new WebSocket(webSocketEndpoint)

            socket.onmessage = function (e) {

                console.log('message', e)
                // alert(e.data)
                var msgData = JSON.parse(e.data);
                console.log(msgData);
                let sender = find_sender(THIS_USERNAME, msgData.user);
                alert(sender);
                chatItems.append(`<div class="msg ${sender}-msg">
              <div class="msg-img" style="background-image: url(${msgData.avatar})"></div>
              <div class="msg-bubble">
                <div class="msg-info">
                  <div class="msg-info-name">${msgData.user}</div>
                  <div class="msg-info-time">${msgData.datetime}</div>
                </div>

                <div class="msg-text">
                  ${msgData.msg}
                </div>
              </div>
        </div>`);
            }

            socket.onopen = function (e) {
                console.log('open', e)
                formData.submit(function (event) {
                    event.preventDefault()
                    var messageText = messageInput.val()
                    console.log(messageText)
                    var jsonData = JSON.stringify({msg: messageText, user: 'jmitchel3'})
                    socket.send(jsonData)
                    formData[0].reset()
                })
            }

            socket.onerror = function (e) {
                console.log('error', e)
            }
            socket.onclose = function (e) {
                console.log('closed', e)
            }


            if (socket.readyState == WebSocket.OPEN) {

            } else if (socket.readyState == WebSocket.CONNECTING) {
                console.log("connecting..")
            }


        })

    </script>
{% endblock %}

chat/templates/chat/inbox.html
{% extends "base.html" %}

{% block content %}


{% endblock %}

chat/templates/chat/thread.html
{% extends "base.html" %}

{% block content %}
    <style>
        .msg {
            display: flex;
            align-items: flex-end;
            margin-bottom: 10px;
        }

        .msg:last-of-type {
            margin: 0;
        }

        .msg-img {
            width: 50px;
            height: 50px;
            margin-right: 10px;
            background: #ddd;
            background-repeat: no-repeat;
            background-position: center;
            background-size: cover;
            border-radius: 50%;
        }

        .msg-bubble {
            max-width: 450px;
            padding: 15px;
            border-radius: 15px;
            background: #ececec;
        }

        .msg-info {
            display: flex;
            justify-content: space-between;
            align-items: center;
            margin-bottom: 10px;
        }

        .msg-info-name {
            margin-right: 10px;
            font-weight: bold;
        }

        .msg-info-time {
            font-size: 0.85em;
        }

        .user-msg .msg-bubble {
            border-bottom-left-radius: 0;
        }

        .my-msg {
            flex-direction: row-reverse;
        }

        .my-msg .msg-bubble {
            background: #579ffb;
            color: #fff;
            border-bottom-right-radius: 0;
        }

        .my-msg .msg-img {
            margin: 0 0 0 10px;
        }

        .msger-inputarea {
            display: flex;
            padding: 10px;
            border-top: 2px solid #ddd;
            background: #eee;
        }

        .msger-inputarea * {
            padding: 10px;
            border: none;
            border-radius: 3px;
            font-size: 1em;
        }

        .msger-input {
            flex: 1;
            background: #ddd;
        }

        .msger-send-btn {
            margin-left: 10px;
            background: rgb(0, 196, 65);
            color: #fff;
            font-weight: bold;
            cursor: pointer;
            transition: background 0.23s;
        }

        .msger-send-btn:hover {
            background: rgb(0, 180, 50);
        }

    </style>
    <h3>Thread for {% if user != object.first %}{{ object.first }}{% else %}{{ object.second }}{% endif %}</h3>
    <div id='chat-items'>
        {% for chat in object.dialogmessage_set.all %}
            <div class="msg {% if chat.user == user %}my{% else %}user{% endif %}-msg">
                <div
                        class="msg-img"
                        style="background-image: url({{ chat.user.avatar.url }})"></div>

                <div class="msg-bubble">
                    <div class="msg-info">
                        <div class="msg-info-name">{{ chat.user }}</div>
                        <div class="msg-info-time">{{ chat.timestamp|date:"d.m.y H:i" }}</div>
                    </div>

                    <div class="msg-text">
                        {{ chat.message }}
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>

    <form id='form' method='POST'> {% csrf_token %}
        {{ form.as_p }}
        <input type='submit' class='btn btn-primary'/>
    </form>



{% endblock %}
{% block javascript %}

    <script>
        let THIS_USERNAME = "{{ user.username }}";

        function find_sender(this_user, sended_user) {
            console.log(this_user, sended_user, this_user === sended_user);
            return this_user === sended_user ? "my" : "user";
        }

        $(document).ready(function () {
            // alert("jquery world")
            let formData = $("#form"),
                messageInput = $("#id_message"),
                chatItems = $('#chat-items'),
                loc = window.location,
                wsStart = "ws://";
            if (loc.protocol == "https:") {
                wsStart = "wss://";
            }
            let webSocketEndpoint = wsStart + loc.host + loc.pathname,  // ws : wss
                socket = new WebSocket(webSocketEndpoint)

            socket.onmessage = function (e) {

                console.log('message', e)
                // alert(e.data)
                var msgData = JSON.parse(e.data);
                console.log(msgData);
                let sender = find_sender(THIS_USERNAME, msgData.user);
                alert(sender);
                chatItems.append(`<div class="msg ${sender}-msg">
              <div class="msg-img" style="background-image: url(${msgData.avatar})"></div>
              <div class="msg-bubble">
                <div class="msg-info">
                  <div class="msg-info-name">${msgData.user}</div>
                  <div class="msg-info-time">${msgData.datetime}</div>
                </div>

                <div class="msg-text">
                  ${msgData.msg}
                </div>
              </div>
        </div>`);
            }

            socket.onopen = function (e) {
                console.log('open', e)
                formData.submit(function (event) {
                    event.preventDefault()
                    var messageText = messageInput.val()
                    console.log(messageText)
                    var jsonData = JSON.stringify({msg: messageText, user: 'jmitchel3'})
                    socket.send(jsonData)
                    formData[0].reset()
                })
            }

            socket.onerror = function (e) {
                console.log('error', e)
            }
            socket.onclose = function (e) {
                console.log('closed', e)
            }


            if (socket.readyState == WebSocket.OPEN) {

            } else if (socket.readyState == WebSocket.CONNECTING) {
                console.log("connecting..")
            }


        })

    </script>
{% endblock %}